twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ["bootstrap_5_layout.html.twig"]
    globals:
        contact_website: '%env(DOMAIN)%'
        contact_company: '%env(COMPANY)%'
        contact_company1: '%env(COMPANY1)%'
        contact_company2: '%env(COMPANY2)%'
        contact_address: '%env(ADDRESS)%'
        contact_zip: '%env(ZIP)%'
        contact_city: '%env(CITY)%'
        contact_phone: '%env(PHONE)%'
        contact_email: '%env(CONTACT_EMAIL)%'
        contact_siret: '%env(SIRET)%'
        contact_country: '%env(COUNTRY)%'
        varKey: varValue
    paths:
        "/public/img": images
when@test:
    twig:
        strict_variables: true
